### Qn 1

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/Rajesh/Edureka/05_numpy_pandas/SalaryGender.csv")
print(df)

np_salary_array = np.array(df["Salary"])
np_gender_array = np.array(df["Gender"])
np_age_array = np.array(df["Age"])
np_phd_array = np.array(df["PhD"])

    Salary  Gender  Age  PhD
0   140.00       1   47    1
1    30.00       0   65    1
2    35.10       0   56    0
3    30.00       1   23    0
4    80.00       0   53    1
5    30.00       0   27    0
6    60.00       1   53    0
7    31.10       0   30    0
8   125.00       1   44    1
9    51.00       1   63    1
10    3.00       1   22    0
11   46.00       1   59    0
12  150.00       1   60    1
13    3.00       1   28    0
14  130.00       1   65    0
15   15.00       0   25    0
16  130.00       1   65    0
17   84.00       0   47    1
18  190.00       1   66    1
19   74.00       1   45    1
20   73.00       0   46    0
21   10.00       0   24    0
22   50.00       0   60    0
23    7.00       0   63    0
24    9.50       0   27    0
25   15.20       1   66    1
26   28.60       1   36    1
27   20.00       0   30    0
28   72.00       0   51    1
29   81.00       1   65    1
..     ...     ...  ...  ...
70   40.70       0   57    0
71   15.00       1   23    0
72    0.25    

### Qn 2

In [2]:
df[(df["Gender"]==1) & (df["PhD"]==1)].count()

Salary    24
Gender    24
Age       24
PhD       24
dtype: int64

### Qn 3

In [3]:
newdf = df[['Age', 'PhD']].copy()
newdf.drop(newdf[newdf["PhD"]!=1].index, inplace=True)
print(newdf)

    Age  PhD
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1


### Qn 4

In [4]:
df[df["PhD"]==1]["PhD"].count()

39

### Qn 5

In [7]:
import numpy as np
a = np.array([0,5,4,0,4,4,3,0,0,5,2,1,1,9])
unique, counts = np.unique(a, return_counts = True)
a_dict = dict(zip(unique, counts))
output = []
for i in range(0,10):
    output.append(a_dict.get(i,0))
print(output)

[4, 2, 1, 1, 3, 2, 0, 0, 0, 1]


### Qn 6

In [10]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(a[a[:]>5])

[ 6  7  8  9 10 11]


### Qn 7

In [18]:
import numpy as np
a = np.array([np.nan, 1., 2., np.nan, 3., 4., 5.])
print(a)
print(a[~np.isnan(a)])

[ nan   1.   2.  nan   3.   4.   5.]
[ 1.  2.  3.  4.  5.]


### Qn 8

In [26]:
import numpy as np
import random
N=10
a = np.random.random((N,N))
print(a)
print('Min Value: ' + str(a.min()))
print('Max Value: ' + str(a.max()))


[[ 0.35613487  0.63831465  0.04834816  0.62929653  0.15664484  0.9833559
   0.8521234   0.96520453  0.5568246   0.53614321]
 [ 0.31905503  0.56433414  0.61749056  0.65686829  0.25524503  0.82500608
   0.79591524  0.0747522   0.37553539  0.60898957]
 [ 0.06967372  0.31058228  0.50141788  0.56758593  0.61906439  0.6455497
   0.13063161  0.24203678  0.4573489   0.38509429]
 [ 0.03883243  0.714773    0.60380195  0.36663165  0.48898869  0.26241028
   0.18467058  0.20225743  0.1314183   0.33715257]
 [ 0.2775613   0.7490607   0.23221167  0.71675946  0.82027562  0.63626659
   0.80338274  0.33254025  0.82145212  0.93287436]
 [ 0.54803053  0.195413    0.10175836  0.19439252  0.1402402   0.46323294
   0.0854538   0.5336074   0.98054826  0.2995682 ]
 [ 0.786794    0.40994818  0.8263269   0.95139808  0.88857106  0.30426514
   0.06637387  0.73072634  0.52223388  0.64362033]
 [ 0.69589416  0.8978087   0.64172182  0.03219425  0.55795977  0.32506875
   0.31448106  0.55890122  0.74920587  0.39517209]
 [

### Qn 9

In [30]:
import numpy as np
x = np.random.random(30)
print(x)
mean = np.mean(x)
print('Mean value for vector is :'+ str(mean))

[ 0.59138368  0.44681763  0.39504353  0.85990888  0.83779524  0.55806078
  0.99006092  0.1469243   0.43569755  0.20658965  0.99510423  0.15016859
  0.41686535  0.96433193  0.82415144  0.16812108  0.71393643  0.80120577
  0.86685783  0.1783704   0.38014902  0.15198164  0.32258824  0.50169843
  0.48452247  0.13504162  0.0199418   0.03016397  0.45215538  0.81982991]
Mean value for vector is :0.494848922357


### Qn 10

In [37]:
import numpy as np
x = np.arange(0,11)
print(x)
op_list = []
for i in x:
    if i >= 3 and i <= 9:
        op = i * -1
    else:
        op = i
    op_list.append(op)

print(op_list)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0, 1, 2, -3, -4, -5, -6, -7, -8, -9, 10]


### Qn 11

In [45]:
import numpy as np
a = np.array([[3,5,1],[7,2,4],[6,9,8]])
print(a)
print(a[a[:,0].argsort()])
print(a[a[:,1].argsort()])
print(a[a[:,2].argsort()])

[[3 5 1]
 [7 2 4]
 [6 9 8]]
[[3 5 1]
 [6 9 8]
 [7 2 4]]
[[7 2 4]
 [3 5 1]
 [6 9 8]]
[[3 5 1]
 [7 2 4]
 [6 9 8]]


### Qn 12

In [52]:
import numpy as np
a = np.arange(72)
a = np.reshape(a,(4,3,2,3))
print(a)
ind = np.lexsort((a[:,1], a[:,2]))
print(a[ind])

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]]


 [[[36 37 38]
   [39 40 41]]

  [[42 43 44]
   [45 46 47]]

  [[48 49 50]
   [51 52 53]]]


 [[[54 55 56]
   [57 58 59]]

  [[60 61 62]
   [63 64 65]]

  [[66 67 68]
   [69 70 71]]]]
[[[[[[ 0  1  2]
     [ 3  4  5]]

    [[ 6  7  8]
     [ 9 10 11]]

    [[12 13 14]
     [15 16 17]]]


   [[[18 19 20]
     [21 22 23]]

    [[24 25 26]
     [27 28 29]]

    [[30 31 32]
     [33 34 35]]]


   [[[36 37 38]
     [39 40 41]]

    [[42 43 44]
     [45 46 47]]

    [[48 49 50]
     [51 52 53]]]]



  [[[[ 0  1  2]
     [ 3  4  5]]

    [[ 6  7  8]
     [ 9 10 11]]

    [[12 13 14]
     [15 16 17]]]


   [[[18 19 20]
     [21 22 23]]

    [[24 25 26]
     [27 28 29]]

    [[30 31 32]
     [33 34 35]]]


   [[[36 37 38]
     [39 40 41]]

    [[42 43 44]
     [45 46 47]]

    [[48 49 50]
     [51 52 53]]]]]




 [[

### Qn 13

In [55]:
import numpy as np
a = np.array([[4,3,1],[5,7,8],[9,5,1],[1,6,7]])
print(a)
a[[0,2]] = a [[2,0]]
print(a)

[[4 3 1]
 [5 7 8]
 [9 5 1]
 [1 6 7]]
[[9 5 1]
 [5 7 8]
 [4 3 1]
 [1 6 7]]


### Qn 14

In [61]:
import numpy as np
a = np.array([[1,2,3,4],[1,8,27,64],[1,4,9,16],[2,4,6,8]])
print(a)
print("Matrix Rank is :", np.linalg.matrix_rank(a))

[[ 1  2  3  4]
 [ 1  8 27 64]
 [ 1  4  9 16]
 [ 2  4  6  8]]
Matrix Rank is : 3


### Qn 15

In [72]:
from IPython.display import display
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/Rajesh/Edureka/05_numpy_pandas/middle_tn_schools.csv")
#display(df)

sorted_df = df.sort_values(by = ['reduced_lunch'], ascending = False)
display(sorted_df)

name  school_rating    size  reduced_lunch  \
188                 McMurray Middle            1.0   740.0           98.0   
197          Moses McKissack Middle            0.0   345.0           98.0   
167         Learning Way Elementary            1.0   575.0           97.0   
107              Haywood Elementary            0.0   842.0           94.0   
65             East Side Elementary            1.0   417.0           93.0   
88             Glengarry Elementary            0.0   472.0           93.0   
248   Robert E. Lilliard Elementary            0.0   400.0           92.0   
226          Park Avenue Elementary            0.0   521.0           91.0   
3                     Bailey Middle            0.0   394.0           91.0   
318               Warner Elementary            0.0   351.0           91.0   
50            Cumberland Elementary            0.0   456.0           91.0   
306             Tusculum Elementary            0.0   722.0           91.0   
28      Cameron College Preparatory            0.0   587.0           90.0   
198        Mountain View Elementary            1.0   485.0           90.0   
94                   Gra-Mar Middle            0.0   406.0           90.0   
138              Jere Baxter Middle            0.0   369.0           90.0   
346                   Wright Middle            0.0   829.0           89.0   
227                 Pearl-Cohn High            0.0   905.0           89.0   
142     John B. Whitsitt Elementary            0.0   517.0           89.0   
180           Margaret Allen Middle            1.0   504.0           89.0   
300              Tom Joy Elementary            0.0   421.0           89.0   
89                 Glenn Elementary            0.0   181.0           88.0   
308                  Una Elementary            1.0   902.0           88.0   
112        Highland Park Elementary            2.0   348.0           88.0   
203                  Murrell School            0.0    71.0           87.0   
90              Glenview Elementary            0.0   798.0           87.0   
136              Jackson Elementary            2.0   519.0           87.0   
63      East End Preparatory School            4.0   383.0           87.0   
151       K I P P Academy Nashville            5.0   349.0           87.0   
246    Robert Churchwell Elementary            0.0   520.0           87.0   
..                              ...            ...     ...            ...   
290              Summit High School            4.0  1319.0           12.0   
0       Allendale Elementary School            5.0   851.0           10.0   
126          Indian Lake Elementary            5.0   555.0           10.0   
78          Fred J Page High School            5.0   937.0            9.0   
314         Walnut Grove Elementary            5.0   662.0            9.0   
281         Station Camp Elementary            5.0  1048.0            9.0   
343      Winstead Elementary School            5.0   515.0            8.0   
56                 Discovery School            5.0   411.0            8.0   
302              Trinity Elementary            5.0   595.0            8.0   
292            Sunset Middle School            5.0   851.0            8.0   
77             Franklin High School            5.0  1747.0            7.0   
291        Sunset Elementary School            5.0   779.0            7.0   
79        Fred J Page Middle School            5.0  1056.0            7.0   
220      Oak View Elementary School            5.0   665.0            6.0   
86              Glendale Elementary            5.0   434.0            6.0   
175             Lipscomb Elementary            5.0   775.0            5.0   
97          Grassland Middle School            5.0   921.0            5.0   
240           Ravenwood High School            4.0  2025.0            4.0   
96             Grassland Elementary            5.0   518.0            4.0   
124         Hunters Bend Elementary            5.0   564.0            4.0   
20            Brentwood Hig

In [74]:
grouped_df = df.groupby('reduced_lunch')
display(grouped_df.first())

name  school_rating  \
reduced_lunch                                                               
2.0                          Clovercroft Elementary School            5.0   
3.0                                Brentwood Middle School            5.0   
4.0                                  Brentwood High School            5.0   
5.0                                Grassland Middle School            5.0   
6.0                                    Glendale Elementary            5.0   
7.0                                   Franklin High School            5.0   
8.0                                       Discovery School            5.0   
9.0                                Fred J Page High School            5.0   
10.0                           Allendale Elementary School            5.0   
12.0                           Homer Pittard Campus School            4.0   
13.0                          Chapman's Retreat Elementary            4.0   
15.0                              Jack Anderson Elementary            5.0   
16.0                                      Beech Elementary            5.0   
17.0                               Renaissance High School            4.0   
18.0                                Erma Siegel Elementary            4.0   
19.0                                   Middle College High            5.0   
20.0                   Hillsboro Elementary/ Middle School            5.0   
21.0                              Beech Senior High School            4.0   
22.0                                 Lake Ridge Elementary            5.0   
23.0                              Mt. Juliet Middle School            5.0   
24.0                                Centennial High School            4.0   
25.0                            Blackman Elementary School            5.0   
26.0                                   Barfield Elementary            4.0   
27.0                  Harold B. Williams Elementary School            4.0   
28.0                                          Meigs Middle            5.0   
29.0                                      Hume - Fogg High            5.0   
30.0                                Blackman Middle School            4.0   
31.0                       Marvin Wright Elementary School            4.0   
32.0                                   Fairview Elementary            5.0   
33.0                      Elzie D Patton Elementary School            4.0   
...                                                    ...            ...   
65.0                                    Dickson Elementary            2.0   
66.0                                 Bluff City Elementary            2.0   
67.0                      Benny C. Bills Elementary School            3.0   
70.0                                Byars Dowdy Elementary            3.0   
71.0                                   Anderson Elementary            2.0   
72.0                                  Black Fox Elementary            3.0   
73.0                              Fall-Hamilton Elementary            1.0   
74.0                             Byrns L Darden Elementary            2.0   
75.0                                  Bellshire Elementary            0.0   
76.0                                     H. G. Hill Middle            2.0   
77.0                                   Lead Prep Southeast            2.0   
78.0                              Ketron Elementary School            1.0   
79.0                                    Central Elementary            1.0   
80.0                                  Inglewood Elementary            0.0   
81.0                                Buena Vista Elementary            0.0   
82.0                                  Harris Middle School            2.0   
83.0                                   Caldwell Elementary            0.0   
84.0           Bradley Academy - An Arts Integrated School            1.0   
85.0                            Carter-Lawrence Elementary            0.0   
86.0                                      Eakin El

In [75]:
print(df['reduced_lunch'].corr(df['school_rating']))

-0.815756737306
