### Qn 1

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/Rajesh/Edureka/05_numpy_pandas/SalaryGender.csv")
print(df)

np_salary_array = np.array(df["Salary"])
np_gender_array = np.array(df["Gender"])
np_age_array = np.array(df["Age"])
np_phd_array = np.array(df["PhD"])

    Salary  Gender  Age  PhD
0   140.00       1   47    1
1    30.00       0   65    1
2    35.10       0   56    0
3    30.00       1   23    0
4    80.00       0   53    1
5    30.00       0   27    0
6    60.00       1   53    0
7    31.10       0   30    0
8   125.00       1   44    1
9    51.00       1   63    1
10    3.00       1   22    0
11   46.00       1   59    0
12  150.00       1   60    1
13    3.00       1   28    0
14  130.00       1   65    0
15   15.00       0   25    0
16  130.00       1   65    0
17   84.00       0   47    1
18  190.00       1   66    1
19   74.00       1   45    1
20   73.00       0   46    0
21   10.00       0   24    0
22   50.00       0   60    0
23    7.00       0   63    0
24    9.50       0   27    0
25   15.20       1   66    1
26   28.60       1   36    1
27   20.00       0   30    0
28   72.00       0   51    1
29   81.00       1   65    1
..     ...     ...  ...  ...
70   40.70       0   57    0
71   15.00       1   23    0
72    0.25    

### Qn 2

In [2]:
df[(df["Gender"]==1) & (df["PhD"]==1)].count()

Salary    24
Gender    24
Age       24
PhD       24
dtype: int64

### Qn 3

In [3]:
newdf = df[['Age', 'PhD']].copy()
newdf.drop(newdf[newdf["PhD"]!=1].index, inplace=True)
print(newdf)

    Age  PhD
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1


### Qn 4

In [4]:
df[df["PhD"]==1]["PhD"].count()

39

### Qn 5

In [7]:
import numpy as np
a = np.array([0,5,4,0,4,4,3,0,0,5,2,1,1,9])
unique, counts = np.unique(a, return_counts = True)
a_dict = dict(zip(unique, counts))
output = []
for i in range(0,10):
    output.append(a_dict.get(i,0))
print(output)

[4, 2, 1, 1, 3, 2, 0, 0, 0, 1]


### Qn 6

In [10]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(a[a[:]>5])

[ 6  7  8  9 10 11]


### Qn 7

In [18]:
import numpy as np
a = np.array([np.nan, 1., 2., np.nan, 3., 4., 5.])
print(a)
print(a[~np.isnan(a)])

[ nan   1.   2.  nan   3.   4.   5.]
[ 1.  2.  3.  4.  5.]


### Qn 8

In [26]:
import numpy as np
import random
N=10
a = np.random.random((N,N))
print(a)
print('Min Value: ' + str(a.min()))
print('Max Value: ' + str(a.max()))


[[ 0.35613487  0.63831465  0.04834816  0.62929653  0.15664484  0.9833559
   0.8521234   0.96520453  0.5568246   0.53614321]
 [ 0.31905503  0.56433414  0.61749056  0.65686829  0.25524503  0.82500608
   0.79591524  0.0747522   0.37553539  0.60898957]
 [ 0.06967372  0.31058228  0.50141788  0.56758593  0.61906439  0.6455497
   0.13063161  0.24203678  0.4573489   0.38509429]
 [ 0.03883243  0.714773    0.60380195  0.36663165  0.48898869  0.26241028
   0.18467058  0.20225743  0.1314183   0.33715257]
 [ 0.2775613   0.7490607   0.23221167  0.71675946  0.82027562  0.63626659
   0.80338274  0.33254025  0.82145212  0.93287436]
 [ 0.54803053  0.195413    0.10175836  0.19439252  0.1402402   0.46323294
   0.0854538   0.5336074   0.98054826  0.2995682 ]
 [ 0.786794    0.40994818  0.8263269   0.95139808  0.88857106  0.30426514
   0.06637387  0.73072634  0.52223388  0.64362033]
 [ 0.69589416  0.8978087   0.64172182  0.03219425  0.55795977  0.32506875
   0.31448106  0.55890122  0.74920587  0.39517209]
 [

### Qn 9

In [30]:
import numpy as np
x = np.random.random(30)
print(x)
mean = np.mean(x)
print('Mean value for vector is :'+ str(mean))

[ 0.59138368  0.44681763  0.39504353  0.85990888  0.83779524  0.55806078
  0.99006092  0.1469243   0.43569755  0.20658965  0.99510423  0.15016859
  0.41686535  0.96433193  0.82415144  0.16812108  0.71393643  0.80120577
  0.86685783  0.1783704   0.38014902  0.15198164  0.32258824  0.50169843
  0.48452247  0.13504162  0.0199418   0.03016397  0.45215538  0.81982991]
Mean value for vector is :0.494848922357


### Qn 10

In [37]:
import numpy as np
x = np.arange(0,11)
print(x)
op_list = []
for i in x:
    if i >= 3 and i <= 9:
        op = i * -1
    else:
        op = i
    op_list.append(op)

print(op_list)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0, 1, 2, -3, -4, -5, -6, -7, -8, -9, 10]
